# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0b93301075f6d5880e866e0962248d2e2a858ce12c29c51c6df20e233116e772a0ed717c3932783845cdf41a17d30db5dda06cd4396ef57606fac33a9538546

test:
  secret_key_base: 07732acafb23e3c69329b00537e02236e13eb209ba18ae042db0fb678f1103647f3f891e4ad4ab0f28b0ed395003d2a5b6bd30fc8ded85f551fc93da50feb7b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
